index.html
style.css

페이지 이동 활성화

---

index.html
main.js
register.html
style.css

로그인 페이지와 js 파일 연동 완료
페이지 이동 기능 js 함수로 바꿈

#4 처음이신가요 색상 변경

---

register/register.html
register/registerData.js
register/registerScript.js
register/registerStyle.css

Kangkyuchang

---

main.js

#21 쿠키(임시)

---

index.html
main.js

쿠키 웹 서버에 정상저장 확인, 로그인 이후 다시 돌아왔을 때 이메일 남아있는것 확인

#24 로그인 페이지 쿠키

---

main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css
main_page/mapValue.js

지도랑 슬라이딩 드로어 구현중

---

main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

슬라이딩 드로어 기능구현

---

lower_bar/lower_bar.html
lower_bar/lower_barScript.js

<script src="./lower_barScript.js" ></script> 만 html에 추가해주면 되고 수정만 하면 모든 곳에서 다 수정한 내용이 적용

하단바 모든 태그 복사 없이 사용 가능

---

main_page/main_page.html
main_page/main_pageStyle.css

슬라이딩 드로어 내부에 위젯 추가 필요
하단바 비율 조정 필요
상단 출발, 목적지 선정 드롭다운 리스트 추가 필요

슬라이딩 드로어 구현(완)

---

main_page/setting_page/setting_page.css
main_page/setting_page/setting_page.html
main_page/setting_page/setting_page.js

세팅페이지 초기 구축

---

login/index.html
login/main.js
login/style.css
main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

인원 조절 이벤트 수정 필요
버튼들 디자인 수정
슬라이딩 드로어 높이 조절
취소 버튼 추가

슬라이딩 드로어 내부 구현중

---

main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

드롭다운 리스트 구현

---

home/home.css
home/home.html

홈화면 디자인 이쁘게

---

main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

드롭다운리스트 이벤트 구현 중

---

main_page/setting_page/setting_page.css
main_page/setting_page/setting_page.html

setting_page.html 비율 조정

---

main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

경로 생성(임시)
->길찾기 api사용해야함
안쓰는 전역변수들 / 코드 정리

마커 관련 구현 완료

---

nav_neumorph/nav_neumorph.css

뉴모로픽 하단 바 수정

---

main_page/dbtest/dbcontest.jsp
main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css
nav_neumorph/nav_neumorph.js

head에 css 링크걸고 바디 끝에 스크립트 걸기 + 지도 화면 디자인 수정 중

하단 내브바 js로 바꿈

---

main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

디자인 틀 거의 잡힌듯

---

main.js
matching_room/matching_roomScript.js
register/register.html
register/registerData.js
register/registerScript.js

회원가입 최종 수정

---

main_page/main_page.html
main_page/main_pageScript.js

폴리라인 리셋 기능 구현필요
출.도착 마커 이미지 필요

지도 최단경로 생성

---

main_page/setting_page/setting.css
main_page/setting_page/setting.html
main_page/setting_page/setting.js
main_page/setting_page/setting_page.css
main_page/setting_page/setting_page.html
main_page/setting_page/setting_page.js

세팅페이지 디자인 최종수정

---

register/registerStyle.css
style.css

로그인, 회원가입 디자인 적용

---

main_page/setting_page/setting_page.css
main_page/setting_page/setting_page.html
main_page/setting_page/setting_page.js

슬라이딩 드로어 적용

---

main_page/setting_page/setting_page.html
main_page/setting_page/setting_page.js

드로어 슬라이딩 구현

---

nav_neumorph/nav_neumorph.js

페이지 로딩 시에 탭 별 색깔 적용
href 값에 없는 링크 접속 시에 색 사라질 수도 있음

뉴모로픽 바 수정(임시)

---

main.js
main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

매칭 페이지 일부 수정

---

chat/chatroom/room.js
chat/chatting.html
chat/chatting.js
home/home.js
matching_room/matching_room.html
matching_room/matching_roomDate.js
matching_room/matching_roomScript.js
matching_room/matching_roomStyle.css
register/registerScript.js
util/utilities.js
util/websocket.js

최적화 완료(나중에 날짜 다르면 날짜도 표시해주는 거 만들어야함)

채팅 웹 소켓으로 구현

---

index.html
main.js
main_page/main_page.html
main_page/main_pageScript.js
main_page/main_pageStyle.css

매칭 지도 페이지 작업 중

---

main_page/main_pageScript.js

목적지 오류나는거 수정

---

home/temperature/temper.css
home/temperature/temper.html
nav_neumorph/nav_neumorph.css

Kimjuhyeong
